n = input('Digite algo: ')
print('Tipo primitivo é:', type(n))
print('So tem letras e numeros? ', n.isalnum())
print('Only have letters? ', n.isalpha())
print('?', n.isascii())
print('?', n.isdigit())
print('Only have lowercase letters?', n.islower())
print('Only have decimals?', n.isdecimal())
print('?', n.isidentifier())
print('Only have number?', n.isnumeric())
print('?', n.isprintable())
print('Only have spaces?', n.isspace())
print('Is capitalized?', n.istitle())
print('Only capital letters?', n.isupper())
