n = input('write : ')
print('Tipo primitivo :', type(n))
print('Only have letters and numbers? ', n.isalnum())
print('Only have letters? ', n.isalpha())
print('?', n.isascii())
print('?', n.isdigit())
print('Only have lowercase letters?', n.islower())
print('Only have decimals?', n.isdecimal())
print('?', n.isidentifier())
print('Only have number?', n.isnumeric())
print('?', n.isprintable())
print('Only have spaces?', n.isspace())
print('Is capitalized?', n.istitle())
print('Only capital letters?', n.isupper())
