n = input('write : ')
print('Is it alphabetic and numeric? ', n.isalnum())
print('Is it just alphabetic? ', n.isalpha())
print('?', n.isascii())
print('?', n.isdigit())
print('?', n.islower())
print('?', n.isdecimal())
print('?', n.isidentifier())
print('?', n.isnumeric())
print('?', n.isprintable())
print('?', n.isspace())
print('?', n.istitle())
print('all letters are capitalized?', n.isupper())
